### ISSUE TITLE
"Cartridge unsuitable for this system" error.

### ISSUE THREAD

**Issue by cjuniorfox** [Fenrir-ode/webserver#4]
I have a Saturn VA15. The white one DIP-switched for the Japan region and most (if not all) of USA's games image downloaded from redump collection have mostly the same behavior.
When I try to load over the network one of those games, hitting the A button, the system hangs with black screen soon after the early "loading" image. Not even the SEGA logo screen appears.
If I hit the CD player key (pressing the x button from the control pad), the console goes to CD player Screen, start the "Checking disk format" and then, the message "Cartridge unsuitable for this system" appears at the screen and the CD+G channel chooser button appears instead of the Start Application button.
strangely, if I use the Action Replay cartridge, I'm able to load the game following the process bellow:

1. Load the game with X button
2. Reset the console
3. Starting the game though the Action Replay menu.  

On the other hand, If I load the SD Card with the same game images and try to run those, the console and the games behave as a expected.

**Comment by Ced2911** [comment]
Check the iso region, webserver does not patch region yet

**Comment by cjuniorfox** [comment]
I verified that and It's correct. The region for the testes ISO was US region, while the console were from Jap region.

**Comment by Ced2911** [comment]
fixed in e66fba17a393ca85a7d9a88c2b3a06b1eab2df97

**Comment by cjuniorfox** [comment]
Great! I'll compile the new version soon to test it.
